(function() {var implementors = {};
implementors["image"] = [{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"image/dxt/struct.DXTReader.html\" title=\"struct image::dxt::DXTReader\">DXTReader</a>&lt;R&gt;",synthetic:false,types:["image::dxt::DXTReader"]},{text:"impl&lt;R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"image/gif/struct.GifReader.html\" title=\"struct image::gif::GifReader\">GifReader</a>&lt;R&gt;",synthetic:false,types:["image::gif::GifReader"]},{text:"impl&lt;R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"image/hdr/struct.HdrReader.html\" title=\"struct image::hdr::HdrReader\">HdrReader</a>&lt;R&gt;",synthetic:false,types:["image::hdr::decoder::HdrReader"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"image/png/struct.PNGReader.html\" title=\"struct image::png::PNGReader\">PNGReader</a>&lt;R&gt;",synthetic:false,types:["image::png::PNGReader"]},{text:"impl&lt;R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"image/tiff/struct.TiffReader.html\" title=\"struct image::tiff::TiffReader\">TiffReader</a>&lt;R&gt;",synthetic:false,types:["image::tiff::TiffReader"]},];
implementors["inflate"] = [{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html\" title=\"trait std::io::BufRead\">BufRead</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"inflate/struct.DeflateDecoderBuf.html\" title=\"struct inflate::DeflateDecoderBuf\">DeflateDecoderBuf</a>&lt;R&gt;",synthetic:false,types:["inflate::reader::DeflateDecoderBuf"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"inflate/struct.DeflateDecoder.html\" title=\"struct inflate::DeflateDecoder\">DeflateDecoder</a>&lt;R&gt;",synthetic:false,types:["inflate::reader::DeflateDecoder"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
