(function() {var implementors = {};
implementors["deflate"] = [{text:"impl&lt;W:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a> for <a class=\"struct\" href=\"deflate/write/struct.DeflateEncoder.html\" title=\"struct deflate::write::DeflateEncoder\">DeflateEncoder</a>&lt;W&gt;",synthetic:false,types:["deflate::writer::DeflateEncoder"]},{text:"impl&lt;W:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a> for <a class=\"struct\" href=\"deflate/write/struct.ZlibEncoder.html\" title=\"struct deflate::write::ZlibEncoder\">ZlibEncoder</a>&lt;W&gt;",synthetic:false,types:["deflate::writer::ZlibEncoder"]},];
implementors["inflate"] = [{text:"impl&lt;W:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a> for <a class=\"struct\" href=\"inflate/struct.InflateWriter.html\" title=\"struct inflate::InflateWriter\">InflateWriter</a>&lt;W&gt;",synthetic:false,types:["inflate::writer::InflateWriter"]},];
implementors["lzw"] = [{text:"impl&lt;W:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a> for <a class=\"struct\" href=\"lzw/struct.LsbWriter.html\" title=\"struct lzw::LsbWriter\">LsbWriter</a>&lt;W&gt;",synthetic:false,types:["lzw::bitstream::LsbWriter"]},{text:"impl&lt;W:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Write.html\" title=\"trait std::io::Write\">Write</a> for <a class=\"struct\" href=\"lzw/struct.MsbWriter.html\" title=\"struct lzw::MsbWriter\">MsbWriter</a>&lt;W&gt;",synthetic:false,types:["lzw::bitstream::MsbWriter"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
