.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TERMIMAGE" "1" "September 2016" "termimage developers" ""
.
.SH "NAME"
\fBtermimage\fR \- Display images in your terminal, kind of
.
.SH "SYNOPSIS"
\fBtermimage\fR \fIOPTIONS\fR <\fIIMAGE\fR>
.
.SH "DESCRIPTION"
Show images in your terminal\.
.
.P
The images are automatically downscaled to the terminal\'s size and their colours are approximated to match the terminal\'s display colours\.
.
.P
With ANSI output this means a 3\-bit colour resolution, with WinAPI \- 4\-bit\.
.
.P
With WinAPI output the output colours are acquired from the console itself, with ANSI output a sane default is assumed\.
.
.SH "OPTIONS"
<\fIIMAGE\fR>
.
.P
Image to display\.
.
.P
The format is guessed from the extension or magic\.
.
.P
\-s \-\-size <\fIsize\fR>
.
.IP "" 4
.
.nf

Output image resolution\.

By default this is autodetected to match the output terminal\'s resolution,
but is required when outputting to a file\.

Format: NxM
.
.fi
.
.IP "" 0
.
.P
\-f \-\-force
.
.IP "" 4
.
.nf

By default the image\'s aspect ratio will be preserved when downscaling,
use this option to override that behaviour\.
.
.fi
.
.IP "" 0
.
.P
\-a \-\-ansi
.
.IP "" 4
.
.nf

Force ANSI output\.

This really applies only on Windows, as there\'s no non\-ANSI alternatives
on other platforms\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBtermimage\fR [\fB\-s\fR \fINxM\fR] [\fB\-f\fR] \fIassets/image\.png\fR
.
.IP "" 4
.
.nf

Display assets/image\.png in the terminal, optionally not preserving
the aspect ratio\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR> and Josh Triplett <\fIjosh@joshtriplett\.org\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/termimage/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/termimage\fR>
